// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIdTEHF0lqneZtbs2u8YkpH5zCEOP3YSI',
    appId: '1:1065656026943:web:1f6556284b06f122d3b58a',
    messagingSenderId: '1065656026943',
    projectId: 'smart-timetable-4371d',
    authDomain: 'smart-timetable-4371d.firebaseapp.com',
    storageBucket: 'smart-timetable-4371d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_FvY4bM0OhdnnVP1PrFzUvmAWVKnDjlg',
    appId: '1:1065656026943:android:58b150d44daca5f5d3b58a',
    messagingSenderId: '1065656026943',
    projectId: 'smart-timetable-4371d',
    storageBucket: 'smart-timetable-4371d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCIaIQYdtPutUn9pKFTDkD9JQ6JoWvGTo8',
    appId: '1:1065656026943:ios:5c0edf1c070af96ed3b58a',
    messagingSenderId: '1065656026943',
    projectId: 'smart-timetable-4371d',
    storageBucket: 'smart-timetable-4371d.firebasestorage.app',
    iosBundleId: 'com.example.smartTimetable',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCIaIQYdtPutUn9pKFTDkD9JQ6JoWvGTo8',
    appId: '1:1065656026943:ios:5c0edf1c070af96ed3b58a',
    messagingSenderId: '1065656026943',
    projectId: 'smart-timetable-4371d',
    storageBucket: 'smart-timetable-4371d.firebasestorage.app',
    iosBundleId: 'com.example.smartTimetable',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDIdTEHF0lqneZtbs2u8YkpH5zCEOP3YSI',
    appId: '1:1065656026943:web:1f6556284b06f122d3b58a',
    messagingSenderId: '1065656026943',
    projectId: 'smart-timetable-4371d',
    authDomain: 'smart-timetable-4371d.firebaseapp.com',
    storageBucket: 'smart-timetable-4371d.firebasestorage.app',
  );
}
