import 'package:cloud_firestore/cloud_firestore.dart';
import '../models/timetable_model.dart';

class FirestoreService {
  final FirebaseFirestore _db = FirebaseFirestore.instance;

  // Save the best timetable generated by the GA to Firestore
  Future<void> saveTimetable(Timetable timetable) async {
    // Clear any previously generated timetable first
    final existing = await _db.collection('timetables').get();
    for (var doc in existing.docs) {
      await doc.reference.delete();
    }

    // Save each slot as a separate Firestore document
    for (var slot in timetable.slots) {
      await _db.collection('timetables').add(slot.toMap());
    }

    print('Timetable saved to Firestore successfully!');
  }

  // Fetch the saved timetable from Firestore
  Future<List<ScheduleSlot>> fetchTimetable() async {
    final snapshot = await _db.collection('timetables').get();
    return snapshot.docs
        .map((doc) => ScheduleSlot.fromMap(doc.data()))
        .toList();
  }

  // Fetch timetable for a specific lecturer only
  Future<List<ScheduleSlot>> fetchLecturerTimetable(String lecturerId) async {
    final snapshot = await _db
        .collection('timetables')
        .where('lecturerId', isEqualTo: lecturerId)
        .get();
    return snapshot.docs
        .map((doc) => ScheduleSlot.fromMap(doc.data()))
        .toList();
  }
}